# Generated by Django 4.2.4 on 2023-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memebers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_level', models.TextField()),
                ('Course_Preference', models.TextField()),
                ('name', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('DOB', models.DateTimeField(auto_now_add=True)),
                ('Addhar_no', models.TextField()),
                ('phone_no', models.TextField()),
                ('email', models.TextField()),
                ('religion', models.TextField()),
                ('minority_Communities', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('minority_Religion', models.TextField()),
                ('Blood_group', models.TextField()),
                ('Mother_language', models.TextField()),
                ('Hostel_required', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('About_us', models.TextField()),
                ('country', models.TextField()),
                ('Address', models.TextField()),
                ('pincode', models.TextField()),
                ('Father_name', models.TextField()),
                ('Father_ph_no', models.TextField()),
                ('Father_Occupation', models.TextField()),
                ('Mother_name', models.TextField()),
                ('Mother_ph_no', models.TextField()),
                ('Mother_Occupation', models.TextField()),
                ('Family_Annual_Income', models.TextField()),
            ],
            options={
                'db_table': 'admission_tbl',
            },
        ),
    ]
