# Generated by Django 4.2.4 on 2023-09-25 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_stu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memebers',
            name='About_us',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Blood_group',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Course_Preference',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Family_Annual_Income',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Father_Occupation',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Father_name',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Father_ph_no',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Hostel_required',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Mother_Occupation',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Mother_language',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Mother_name',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='Mother_ph_no',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='country',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='entry_level',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='minority_Communities',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='minority_Religion',
        ),
        migrations.RemoveField(
            model_name='memebers',
            name='pincode',
        ),
    ]
