# Generated by Django 4.2.4 on 2023-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_memebers_gender_memebers_blood_memebers_cource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memebers',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
