# Generated by Django 4.2.4 on 2023-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_memebers_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='memebers',
            name='marksheet',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='memebers',
            name='photo',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='memebers',
            name='approval',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
