# Generated by Django 4.2.4 on 2023-12-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_memebers_marksheet_memebers_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memebers',
            name='marksheet',
            field=models.ImageField(null=True, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='memebers',
            name='photo',
            field=models.ImageField(null=True, upload_to='static'),
        ),
    ]
